version: "3"
services:
  calcapp:
    build: /calcapp
    image: docker.io/icarly/paskirstytos:0.2
    ports:
      - "8080"
    deploy:
      replicas: 5

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - calcapp
    ports:
      - "80:80"
  # prometheus:
  #     image: docker.io/prom/prometheus:v2.52.0
  #     container_name: prometheus
  #     ports:
  #       - "9090:9090"
  #     command: "--config.file=/etc/prometheus/prometheus.yaml"
  #     volumes:
  #       - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #       - prometheus-data:/prometheus
  #     restart: unless-stopped     
  # grafana:
  #   image: docker.io/grafana/grafana-oss:11.0.0
  #   container_name: grafana
  #   environment:
  #     - "GF_DEFAULT_APP_MODE=development"
  #     - "GF_LOG_LEVEL=debug"
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
  #     - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
  #     - GF_AUTH_BASIC_ENABLED=false # removes login 2/2
  #     - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   restart: unless-stopped 
# volumes:
#   grafana-data:
#     driver: local
#   prometheus-data:
#     driver: local




#TO Do:
# didele apkrova "Apache JMeter naudojant
   
#Read me
#Dokumentacija?

#Vaizdo įrašas ar gyvai ?
#Rodyti kad uzklausos nueina i skirtingus konteinerius

#clean up

#Good source: https://www.youtube.com/watch?v=42Q65H8ch7U